Prevent to generate invalid ruby code on embedded heredoc
Problem
======

Slim generates invalid ruby code if `ruby:` block has a heredoc at end.

For example:

```bash
$ cat test.slimo
ruby:
  v = <<-MSG
  foobar
  MSG
= v

$ slimrb test.slim
SyntaxError: test.slim:8: can't find string "MSG" anywhere before EOF
test.slim:2: syntax error, unexpected end-of-input, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
; v = <<-MSG
            ^
  Use --trace for backtrace.
```

This cause is a semicolon after delimiter of heredoc(`MSG`).

```bash
$ slimrb -c test.slim
_buf = '';
; v = <<-MSG
foobar
MSG;
; _buf << ((::Temple::Utils.escape_html((v))).to_s);
; _buf
```

Heredoc delimiter does not allow putting a semicolon after the delimiter.
So, slim generates invalid ruby code from the example.

Solution
=====

Add a newline to embedded ruby code.

For example:

```ruby
$ slimrb test.slim
foobar

$ slimrb -c test.slim
_buf = '';
; v = <<-MSG
foobar
MSG
;
; _buf << ((::Temple::Utils.escape_html((v))).to_s);
; _buf
```